[package]
name = "vc2-assembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gumdrop = "0.8.1"

[dev-dependencies]
pretty_assertions = "1.4.0"

