#!/bin/bash

mkdir -p tmp
cd tmp
cargo r --bin vc2-image-asm $(ls ../images/*.png)
for i in $(ls *.asm); do
    echo "    jmp [image_draw_return_address]" >> $i
done
cat *.asm > sprites.asm
cd ..

echo "jmp main" >> out.asm
echo "%offset 0xE0000" >> out.asm
cat blackjack.asm >> out.asm
cat tmp/sprites.asm >> out.asm

rm -r tmp
